### ISSUE TITLE
how to setup + error

### ISSUE THREAD

**Issue by dragonGRaf1312** [PiggyAwesome/Streak-Maker#1]
error:
![image](https://user-images.githubusercontent.com/65346683/229259039-1c31f0d4-9cbe-4009-9958-ab086a2efaa0.png)
do i need to change anything? maybe to my own page or something?
![image](https://user-images.githubusercontent.com/65346683/229259047-b659e179-6217-452f-b728-9017c826def3.png)

**Comment by PiggyAwesome** [comment]
Thanks for notifying me. I will fix the program soon

**Comment by dragonGRaf1312** [comment]
> Thanks for notifying me. I will fix the program soon

thx please notify me when fixed

**Comment by dragonGRaf1312** [comment]
currently wont use it but lmk when its fixed might come back then @PiggyAwesome
